
export const ADD_LOCATION   = "ADD_LOCATION";

// LOGIN REDUCER 
export const ADD_USER             = "ADD_USER";
export const UPDATE_USER          = "UPDATE_USER";
export const SET_CURRENT_USER     = "SET_CURRENT_USER";
export const AUTHENTICATING_USER  = "AUTHENTICATING_USER";
export const AUTHENTICATED_USER   = "AUTHENTICATED_USER";
export const FAILED_LOGIN         = "FAILED_LOGIN";
export const LOG_OUT              = "LOG_OUT";

//JOB REDUCER 
export const ADD_JOB        = "ADD_JOB"
export const EDIT_JOB       = "EDIT_JOB";
export const UPDATE_JOB     = "UPDATE_JOB"
export const GET_JOBS       = "GET_JOBS";
export const GET_WEEK       = "GET_WEEK";
export const CREATE_JOB_FLAG= "CREATE_JOB_FLAG"
export const CREATE_JOB     = "CREATE_JOB";

//TEAMS REDUCER
export const GET_TEAMS  = "GET_TEAMS";
export const SET_TEAM = "SET_TEAM";
export const CHANGE_TEAM_EDIT_FLAG = "CHANGE_TEAM_EDIT_FLAG";
export const EDIT_TEAM = "EDIT_TEAM"
export const CHANGE_TEAM_CREATE_FLAG = "CHANGE_TEAM_CREATE_FLAG";
export const CREATE_TEAM = "CREATE_TEAM";
export const CREATE_EDIT_TEAM_FALSE = "CREATE_EDIT_TEAM_FALSE";


//TEAM MEMBER REDUCER 
export const GET_TEAM_MEMBERS = "GET_TEAM_MEMBERS";
export const SET_TEAM_MEMBER  = "SET_TEAM_MEMBER";
export const EDIT_TEAM_MEMBER = "EDIT_TEAM_MEMBER";
export const CHANGE_TEAM_MEMBER_EDIT_FLAG = "CHANGE_TEAM_MEMBER_EDIT_FLAG";
export const CREATE_TEAM_MEMBER_FLAG = "CREATE_TEAM_MEMBER_FLAG";
export const CREATE_TEAM_MEMBER = "CREATE_TEAM_MEMBER";
export const CREATE_EDIT_MEMBER_FALSE = "CREATE_EDIT_MEMBER_FALSE";


//CUSTOMER REDUCER
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const EDIT_CUSTOMER_FLAG = "EDIT_CUSTOMER_FLAG";
export const EDIT_CUSTOMER = "EDIT_CUSTOMER";
export const ADD_CUSTOMER_TO_EDIT = "ADD_CUSTOMER_TO_EDIT";
export const CREATE_CUSTOMER_FLAG = "CREATE_CUSTOMER_FLAG";
export const CREATE_CUSTOMER = "CREATE_CUSTOMER";

//COMPANIES REDUCER 
export const GET_COMPANIES = "GET_COMPANIES";
export const ADD_COMPANY = "ADD_COMPANY";